baseURL = "https://peiel.com/"
relativeURLs = true
theme = "LoveIt"
title = "源码赏析"
defaultContentLanguage = "zh-cn"
disableHugoGeneratorInject = true
enableRobotsTXT = true
enableGitInfo = true
enableEmoji = true
hasCJKLanguage = true
paginate = 14
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
timeZone = "Asia/Shanghai"
LanguageCode = "zh-CN"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "rss"
    pre = "<i class='fas fa-rss fa-fw'></i>"
    url = "/index.xml"
    title = "RSS"
    weight = 18
  [[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-fw'></i>"
    url = "https://github.com/peiel"
    title = "GitHub"
    weight = 20

[params]
  defaultTheme = "auto"  # 网站默认主题 ("light", "dark", "auto")
  gitRepo = "https://github.com/peiel/blog"
  dateFormat = "2006-01-02"
  images = ["/images/logo.jpg"]
  description = "编程 学习 生活 分享"
  keywords = []
  author = "peiel"
  webmanifest = "/site.webmanifest"
  swjs = "/sw.js"

  [params.app]
    title = "源码赏析"
    noFavicon = false
    svgFavicon = ""
    themeColor = "#ffffff"
    iconColor = "#5bbad5"
    tileColor = "#da532c"
  [params.search]
    enable = false
    # type of search engine ["lunr", "algolia"]
    type = "lunr"
    # max index length of the chunked content
    contentLength = 4000
    # placeholder of the search bar
    placeholder = ""
    #  max number of results length
    maxResultLength = 10
    #  snippet length of the result
    snippetLength = 30
    #  HTML tag name of the highlight part in results
    highlightTag = "em"
    #  whether to use the absolute URL based on the baseURL in search index
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""


  [params.home]
    rss = 10  # RSS 文章数目
    [params.home.profile]
      avatarURL = "images/logo.jpg"
      altLogoURL = "https://peierlong-blog.oss-cn-hongkong.aliyuncs.com/uPic/logo.JPG"
      title = "源码赏析"
      subtitle = "Welcome to my blog!"
    [params.home.posts]
      paginate = 2
  [params.social]
    GitHub = "peiel"
    Email = "peielcn@gmail.com"

  [params.header]
    desktopMode = "fixed"   # 桌面端导航栏模式 ("fixed", "normal", "auto")
    mobileMode = "auto"  # 移动端导航栏模式 ("fixed", "normal", "auto")
    # 页面头部导航栏标题配置
    [params.header.title]
      logo = "" # LOGO 的 URL
      name = "源码赏析" # 标题名称
      pre = "" # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标  #"<i class='far fa-kiss-wink-heart fa-fw'></i>"  
      post = ""  # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标

  # 页面底部信息配置
  [params.footer]
    enable = true
    custom = ''
    hugo = false  # 是否显示 Hugo 和主题信息
    copyright = true  # 是否显示版权信息
    author = true  # 是否显示作者
    since = 2015 # 网站创立年份
    icp = "京ICP备2020043775号-1" # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    # 许可协议信息 (支持 HTML 格式)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    statistic = """"""

  # Section (所有文章) 页面配置
  [params.section]
    paginate = 20  # list 页面每页显示文章数量
    dateFormat = "01-02"  # 日期格式 (月和日)
    rss = 10  # RSS 文章数目

  # List (目录或标签) 页面配置
  [params.list]
    paginate = 20  # list 页面每页显示文章数量
    dateFormat = "01-02"  # 日期格式 (月和日)
    rss = 10  # RSS 文章数目

  [params.page]
    hiddenFromHomePage = false    # 是否在主页隐藏
    hiddenFromSearch = false  # 是否在搜索结果中隐藏
    lightgallery = true  # 是否使用 lightgallery
    fraction = false  # 是否使用 fraction 扩展语法
    linkToMarkdown = true  # 是否显示原始 Markdown 文档内容的链接
    rssFullText = true  # 是否在 RSS 中显示全文内容
    [params.page.toc]
      enable = true  # 是否使用目录
      keepStatic = false  # 是否保持使用文章前面的静态目录
      auto = true  # 是否使侧边目录自动折叠展开
    [params.page.code]
      copy = true  # 是否显示代码块的复制按钮
      maxShownLines = 100 # 默认展开显示的代码行数
    # Social share links in post page
    [params.page.share]
      enable = true
      Twitter = true
      Whatsapp = false
      Tumblr = true
      Evernote = true
    [params.page.library]
      [params.page.library.css]
        # someCSS = "some.css"
        # located in "assets/" 位于 "assets/"
        # Or 或者
        # someCSS = "https://cdn.example.com/some.css"
      [params.page.library.js]
        # someJavascript = "some.js"
        # located in "assets/" 位于 "assets/"
        # Or 或者
        # someJavascript = "https://cdn.example.com/some.js"
    [params.page.seo]
      images = ["/images/logo.jpg"]
      # 出版者信息
      [params.page.seo.publisher]
        name = "peiel"
        logoUrl = "https://peiel.com/images/logo.jpg"

  # [params.comment]
  #     enable = true
  #     [params.comment.giscus]
  #       enable = true
  #       repo = "zu1k/blog"
  #       repoId = "MDEwOlJlcG9zaXRvcnkzMDExMDQ1OTU="
  #       category = "Comments"
  #       categoryId = "DIC_kwDOEfJ9084CA02V"
  #       mapping = "og:title"
  #     [params.comment.utterances]
  #       enable = false
  #       repo = "zu1k/comment"
  #       issueTerm = "url"
  #       label = "blog"
  #       lightTheme = "github-light"
  #       darkTheme = "github-dark"

[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

[author]
  name = "Peiel"
  email = "peielcn@gmail.com"
  link = "https://peiel.com"

[sitemap]
  changefreq = "always"
  filename = "sitemap.xml"
  priority = 1

[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
