on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["notion-to-md"]
    types:
      - completed
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

name: deploy-to-aliyun

jobs:
  deploy-to-aliyun:
    runs-on: ubuntu-latest
    container: centos:7
    steps:

    # 切换分支
    - name: Checkout
      uses: actions/checkout@main

    # Update references
    - name: Git Sumbodule Update
      run: |
        git submodule update --init

    # 使用 node:16
    - name: use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    
    # install hugo
    - name: install hugo
      run: |
        sudo apt-get install hugo
      env:
        CI: true
    
    # build
    - name: hugo build
      run: |
        hugo
        ls -al public
      env:
        CI: true

    # Deploy
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ALI_ACCESS_TOKEN }}
        ARGS: "-avz --delete"
        SOURCE: "public/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.TARGET }}
