on: [workflow_dispatch, watch]

name: notion_hexo_to_aliyun

jobs:
  notion_hexo_to_aliyun:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: false

    - uses: mohuishou/notion-blog-actions/notion@main
      with:
        token: ${{ secrets.NOTION_TOKEN }}
        token_v2: ${{ secrets.NOTION_TOKEN_V2 }}
        space_id: "f4ce1ccb830e4052af32394aa5dbe1c4"
        database_id: "f4ce1ccb830e4052af32394aa5dbe1c4"
        output: "./tmp/"

    - name: "migrate image"
      uses: mohuishou/notion-blog-actions/migrate@main
      with:
        input: "./tmp/*.md"

    - name: "cp md files"
      run: |
        cp -f tmp/*.md source/_posts/notion/
        rm -rf tmp

    - name: git setting
      run: |
        git config --global user.email "erick.el.pei@gmail.com"
        git config --global user.name "Erick"

    # 切换分支
    - name: Checkout
      uses: actions/checkout@main
    # 下载 git submodule
    - uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    # 使用 node:16
    - name: use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    
    # npm install
    - name: npm install
      run: |
        npm install -g hexo-cli
        npm install
        npm un hexo-renderer-marked
        npm install hexo-renderer-pandoc
      env:
        CI: true
    
    # build
    - name: hexo build
      run: |
        hexo clean
        hexo generate
      env:
        CI: true

    # Deploy
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
        ARGS: "-avz --delete"
        SOURCE: "public/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.TARGET }}
