on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["notion-to-md"]
    types:
      - completed

name: deploy-to-aliyun

jobs:
  deploy-to-aliyun:
    runs-on: ubuntu-latest
    steps:
    # 切换分支
    - name: Checkout
      uses: actions/checkout@main
    # 使用 node:16
    - name: use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
    
    # npm install
    - name: npm install
      run: |
        npm install -g hexo-cli
        npm install
        sudo apt-get install pandoc
      env:
        CI: true
    
    # build
    - name: hexo build
      run: |
        hexo clean
        hexo generate
      env:
        CI: true

    # Deploy
    - name: Deploy
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.ALI_ACCESS_TOKEN }}
        ARGS: "-avz --delete"
        SOURCE: "public/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.TARGET }}
