on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["notion-to-md"]
    types:
      - completed

name: deploy-to-aliyun

jobs:
  deploy-to-aliyun:
    runs-on: ubuntu-latest
    steps:

#    # 切换分支
#    - name: Checkout
#      uses: actions/checkout@main
#
#    # Update references
#    - name: Git Sumbodule Update
#      run: |
#        git submodule update --init --recursive
#
#    - name: Setup hugo
#      uses: peaceiris/actions-hugo@v2
#      with:
#        hugo-version: "0.104.3"
#
#    - name: Build
#      # remove --minify tag if you do not need it
#      # docs: https://gohugo.io/hugo-pipes/minification/
#      run: |
#        hugo
#        hugo mod graph
#
#    # Deploy
#    - name: Deploy
#      uses: easingthemes/ssh-deploy@v2.0.7
#      env:
#        SSH_PRIVATE_KEY: ${{ secrets.ALI_ACCESS_TOKEN }}
#        ARGS: "-avz --delete"
#        SOURCE: "public/"
#        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#        REMOTE_USER: ${{ secrets.REMOTE_USER }}
#        TARGET: ${{ secrets.TARGET }}

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.ALI_ACCESS_TOKEN }}
        port: 22
        script: |
          ls -al
