on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["notion-to-md"]
    types:
      - completed

name: deploy-to-aliyun

jobs:
  deploy-to-aliyun:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.ALI_ACCESS_TOKEN }}
        port: 22
        script: |
          cd blog
          git pull
          git submodule update --init
          hugo
          rm -rf /usr/local/nginx/html/*
          mv public/* /usr/local/nginx/html/
