on: 
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

name: notion-to-md

jobs:
  notion-to-md:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: false

    - uses: erick-pei/notion-blog-actions/notion@main
      with:
        token: ${{ secrets.NOTION_TOKEN }}
        token_v2: ${{ secrets.NOTION_TOKEN_V2 }}
        space_id: "f4ce1ccb830e4052af32394aa5dbe1c4"
        database_id: "f4ce1ccb830e4052af32394aa5dbe1c4"
        output: "./tmp/"

    - name: "migrate image"
      uses: erick-pei/notion-blog-actions/migrate@main
      with:
        input: "./tmp/*.md"

    - name: "cp md files"
      run: |
        cp -f tmp/*.md source/_posts/notion/
        rm -rf tmp

    - name: git setting
      run: |
        git config --global user.email "erick.el.pei@gmail.com"
        git config --global user.name "Erick"

    - name: update blog
      run: |
        git add source
        git commit -m "feat: auto update by notion sync"
        git push
