on: 
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

name: notion-to-md

jobs:
  notion-to-md:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: false

    - uses: peiel/notion-blog-actions/notion@main
      with:
        token: ${{ secrets.NOTION_TOKEN }}
        token_v2: ${{ secrets.NOTION_TOKEN_V2 }}
        space_id: "3831fe52536e42ab8b00f6bb3ce041a3"
        database_id: "3831fe52536e42ab8b00f6bb3ce041a3"
        output: "./tmp/"

    # - name: "migrate image"
    #   uses: peiel/notion-blog-actions/migrate@main
    #   with:
    #     input: "./tmp/*.md"

    - name: "cp md files"
      run: |
        cp -f ./tmp/*.md ./content/posts/
        rm -rf ./tmp

    - name: git setting
      run: |
        git config --global user.email "peiel@gmail.com"
        git config --global user.name "peiel"

    - name: update blog
      run: |
        git add .
        git commit -m "feat: auto update by notion sync"
        git push
